#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: phpize
# autospec version: v3
# autospec commit: c1050fe
#
Name     : php-svm
Version  : 0.2.3
Release  : 50
URL      : https://pecl.php.net//get/svm-0.2.3.tgz
Source0  : https://pecl.php.net//get/svm-0.2.3.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: php-svm-lib = %{version}-%{release}
Requires: php-svm-license = %{version}-%{release}
BuildRequires : buildreq-php
BuildRequires : perl(Getopt::Long)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
[![Build Status](https://travis-ci.com/ianbarber/php-svm.svg?branch=master)](https://travis-ci.com/ianbarber/php-svm) (Travis)

%package lib
Summary: lib components for the php-svm package.
Group: Libraries
Requires: php-svm-license = %{version}-%{release}

%description lib
lib components for the php-svm package.


%package license
Summary: license components for the php-svm package.
Group: Default

%description license
license components for the php-svm package.


%prep
%setup -q -n svm-0.2.3
cd %{_builddir}/svm-0.2.3
pushd ..
cp -a svm-0.2.3 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
phpize
%configure --disable-static
make  %{?_smp_mflags}

%install
mkdir -p %{buildroot}/usr/share/package-licenses/php-svm
cp %{_builddir}/svm-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/php-svm/1fa34750b71fa2e95741c06ce78485cc20b24637 || :
cp %{_builddir}/svm-%{version}/libsvm/COPYRIGHT %{buildroot}/usr/share/package-licenses/php-svm/c0269f7355919b74c2e55c405e2b3c8af2554bc1 || :
%make_install

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/extensions/no-debug-non-zts-20230831/svm.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/php-svm/1fa34750b71fa2e95741c06ce78485cc20b24637
/usr/share/package-licenses/php-svm/c0269f7355919b74c2e55c405e2b3c8af2554bc1
